{{- if and (not .Values.psql.enabled) .Values.db.postgres.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgtest.fullname" . }}-dbcreds
  labels:
{{ include "pgtest.labels" . | indent 4 }}
type: Opaque
data:
  password: {{ .Values.db.postgres.password | b64enc }}
{{- end -}}
